import TheArchiveMessage from "../../../components/TheArchiveMessage"

export default function TwentyTwentyOneChristmasEthan() {
    return (
        <TheArchiveMessage
            title="2021 christmas - ethan"
            date="12/25/2021"
            message={`Hi uyen,\n
            Merry Christmas and happy new year! I hope you’ve been enjoying the holidays with your family and enjoying the break so far. I just wanted to write about a few things on my mind about you and how appreciative i am having you in my life. I really don’t express this that much and I feel I need to do so more. \n
            So far this break I feel like I’ve been missing something. Without you now I feel emptier? Life just feels so drastically different without you here by my side and I miss you so much. I’m just constantly counting down the days till I see you again… And I feel this way probably because of how much time we spent with each other this past semester and am just so used to your presence. This semester alone, I have 531 photos of you in my camera roll. To put this in perspective, I have 2.5k photos of me spanning back to 2013. Only 634 of bryan and 517 of Joseph ever. At this rate, there’ll be 3186 photos of you in just 3 years (3 years is how long I’ve known Bryan and Joseph). More photos than I have of me for the past 8 years… This just shows how such a big part of my life you are. You are shaping and changing my life in so many ways. Bringing new memories, perspectives, and feelings into my life. You mean the world to me and I don’t want to lose you anytime soon.\n
            This semester, I got to know you so much better. From learning about your small quirks that I now know and love (like your loud and constant burps lol) to the bigger and deeper parts of your life, I really got to find out who Uyen Phan is all about. I’m glad we really got to get comfortable with one another this semester and be able to share so much about ourselves. Thank you for all the smiles, good memories, joy, happiness, laughter, warmth, and love you’ve brought to my life.\n
            One big thing I learned a lot more about this semester is your own struggles and insecurities. To be honest, this was a big surprise to me - when you opened up about your yearly tears and what it was about. You always seems so happy and such a strong person that I wasn’t expecting that. But I truly hope you know how inspirational you are to me. Hearing about how you worked a job so you weren’t a “burden” to your family, dealing with issues at home, \n
            attending 6 hour per day practice, taking the hardest classes at your school, staying up late at night to study for tests or AP exams, self learning a month of school material, juggling multiple extracurricular activity like your clubs, having a great social life, and STILL preforming well enough in school to attend the best public university in the world? And then you are now at berkeley studying your ass off day in day out. And even though you may feel insecure about who you are, you still push through it and push yourself to the limit while others are giving up on their goals and aspirations and not trying anymore. You’re double majoring in Cog Sci and Data Science. You’re teaching classes about design and young generations about it. You’re a go getter, someone who doesn’t just sit back and lets stuff come to you. You go out there and do what’s need to be done regardless of how much work and dedication it’ll require. You are literally the GOAT when it comes to hard work and resilience. You are one of the stronkest people I know and I hope you truly know that! What you have accomplished might seem not that big of a deal to you, because you lived it. But to everyone else, it’s amazing and says so much about who you are. \n
            I made a bracelet for you. It’s kinda ugly lol. But if you wear it, I want it to remind you of your capabilities, your never ending determination, your smartness, your hard work that you put in to get you to where you are now. You shouldn’t be questioning who you are or your capabilities or your accomplishments. As we both know that whatever you put your mind to, you’ll achieve it no matter what.
            `}
        />
    )
}